name = "honcstore"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL = "postgresql://honcstore_owner:O4g5XeGvVCFJ@ep-dawn-dust-a2gxf6ot.eu-central-1.aws.neon.tech/honcstore?sslmode=require"
JWT_SECRET = "kaasbroodje"
SALT_ROUNDS = 10


# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
