name = "honcstore"
compatibility_date = "2023-12-01"
pages_build_output_dir = "dist"

[vars]
JWT_SECRET = "kaasbroodje"
SALT_ROUNDS = 10
# PROD = true

# [site]
# bucket = "./dist"


# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

# [[d1_databases]]
# binding = "DB"
# database_name = "my-database"
# database_id = ""

# [ai]
# binding = "AI"
